/run/initialize

/vis/open OGL
/vis/drawVolume

/vis/viewer/set/background black
/vis/viewer/set/lightsMove cam
/vis/viewer/set/viewpointThetaPhi 60 45

# -------------------------------------------------------------------
# QUỸ ĐẠO VÀ MÀU SẮC
# -------------------------------------------------------------------
/vis/scene/add/trajectories smooth
/vis/scene/endOfEventAction accumulate 100

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set gamma green
/vis/modeling/trajectories/drawByParticleID-0/set e- red
/vis/modeling/trajectories/drawByParticleID-0/set alpha yellow



# -------------------------------------------------------------------
# ÉP PHÂN RÃ VÀ CẤU HÌNH NGUỒN
# -------------------------------------------------------------------
# 1. Ép các hạt có chu kỳ bán rã cực dài (như Cs-137) PHẢI phân rã
/process/had/rdm/thresholdForVeryLongDecayTime 1.0e+60 year

# 2. Đặt nguồn
/gps/pos/type Point
/gps/pos/centre 0 0 0 cm
/gps/ang/type iso
/gps/particle ion
#/gps/ion 27 60 0 0 
/gps/ion 92 238 0 0
#/gps/ion 88 226 0 0 #Radi
#/gps/ion 90 232 0 0 #Thori
#/gps/ion 55 137 0 0
#/gps/ion 11 22 0 0 #Sodium 22 => will see pair production
#/gps/ion 4 7 0 0 # Li test 
#Cho động năng cực nhỏ (1 eV) để hệ thống nhận diện
/gps/energy 1 eV 

/run/beamOn 1